reddit-clone/config/routes.rb
Reddit::Application.routes.draw do
  root to: 'subs#index'
  resources :users
  resource :session, only: [:new, :destroy, :create]
  resources :subs, except: :destroy do
    resources :posts, only: :new
  end
  resources :posts, except: [:index, :destroy, :new] do
    resources :comments, only: :new
  end
  resources :comments, only: :create

end

reddit-clone/app/models/comment.rb
class Comment < ActiveRecord::Base
  has_many :child_comments,
    class_name: "Comment",
    foreign_key: :parent_comment_id,
    primary_key: :id
  belongs_to :parent_comment,
    class_name: "Comment",
    foreign_key: :parent_comment_id,
    primary_key: :id
  belongs_to :post
  belongs_to :author, class_name: "User"
  validates :author_id, :post_id, :content, presence: true

end

reddit-clone/app/models/post.rb
class Post < ActiveRecord::Base
  # belongs_to :sub
  belongs_to :author, class_name: "User"
  has_many :post_subs, inverse_of: :post, dependent: :destroy
  has_many :subs,
    through: :post_subs,
    source: :sub
  has_many :comments

  validates :title, :author_id, presence: true
  validate :url_or_content


  # private

  def url_or_content
    if url.blank? && content.blank?
      errors[:error] << "Please provide a URL or Content"
    elsif !url.blank? && !content.blank?
      errors[:error] << "Please provide either a URL or Content, not both"
    end
  end



end

reddit-clone/app/models/post_sub.rb
class PostSub < ActiveRecord::Base
  belongs_to :sub
  belongs_to :post
  validates :sub_id, :post, presence: true

end

reddit-clone/app/models/sub.rb
class Sub < ActiveRecord::Base
  has_many :posts,
    through: :post_subs,
    source: :post
  has_many :post_subs, dependent: :destroy
  belongs_to :moderator, class_name: "User"
  validates :title, :description, :moderator_id, presence: true
end

reddit-clone/app/models/user.rb
class User < ActiveRecord::Base
  has_many :subs,
    class_name: "Sub",
    foreign_key: :moderator_id,
    primary_key: :id,
    dependent: :destroy
  has_many :posts,
    class_name: "Post",
    foreign_key: :author_id,
    primary_key: :id,
    dependent: :destroy

  validates :username, presence: true, uniqueness: true
  validates :password_digest, presence: true, uniqueness: true
  validates :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def self.find_by_credentials(username, password)
    @user = User.find_by(username: username)
    return nil if @user.nil?
    @user.is_password?(password) ? @user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    save!
    session_token
  end


end

reddit-clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def redirect_nonauthor
    if Post.find(params[:id]).author_id != current_user.id
      flash[:errors] = ["You are not the author of this post"]
      redirect_to post_url(params[:id])
    end
  end

  def redirect_nonmoderator
    if Sub.find(params[:id]).moderator_id != current_user.id
      flash[:errors] = ["You are not the moderator of this sub"]
      redirect_to sub_url(params[:id])
    end
  end


  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logged_in?
    !!current_user
  end

end

reddit-clone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new

  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    if @comment.save
      redirect_to post_url(@comment.post_id)
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to post_url(@comment.post_id)
    end
  end


  def comment_params
    params.require(:comment).permit(:content, :parent_comment_id, :post_id)

end

reddit-clone/app/controllers/concerns/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    username = params[:user][:username]
    password = params[:user][:password]
    @user = User.find_by_credentials(username, password)
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Incorrect Username/Password Combination"]
      render 'new'
    end
  end

  def new
    render :new
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

end

reddit-clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :redirect_nonauthor, only: [:update, :edit]

  def new
    @post = Post.new
    @subs = Sub.all
    render :new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def edit
    @post = Post.find(params[:id])
    @subs = Sub.all
    render :edit
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:author)
    render :show
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, :author_id, sub_ids: [])
  end


end

reddit-clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :redirect_nonmoderator, only: [:edit, :update]

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def show
    @sub = Sub.find(params[:id])
    @posts = @sub.posts.includes(:author)
    render :show
  end

  def index
    @subs = Sub.all.includes(:moderator)
    render :index
  end


  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description, :moderator_id)
  end

end

reddit-clone/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def index
    @users = User.all
    render :index
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

reddit-clone/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    <<-html.html_safe
      <input type='hidden' name='authenticity_token' value="#{form_authenticity_token}">
    html
  end
end

reddit-clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    <a href=" <%= user_url(current_user) %> "><p><%= current_user.username %></p></a>
    <form action="<%= session_url %>" method="post">
      <%= auth_token %>
      <input type="hidden" name="_method" value="delete">
      <input type="submit" name="Logout" value="Logout">
    </form>
    <% else %>
      <a href="<%= new_session_url %>">Login</a>
      <a href="<%= new_user_url %>">Signup</a>
    <% end %>
    <a href="<%= root_url %>"><h1>Reddit</h1></a>

<%= yield %>

</body>
</html>

reddit-clone/app/views/subs/_form.html.erb
<% action = (sub.persisted? ? sub_url(sub) : subs_url) %>
<% method = (sub.persisted? ? 'PATCH' : 'POST') %>

<form action=" <%= action %> " method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <%= auth_token %>

  <table>
    <tr>
      <td>
        <label for="sub_title">Title:</label>
      </td>
      <td>
        <input type="text" name="sub[title]" value="<%= sub.title %>">
      </td>
    </tr>
    <tr>
      <td>
        <label for="sub_description">Description:</label>
      </td>
      <td>
        <input type="text" name="sub[description]" value="<%= sub.description %>">
      </td>
    </tr>
  </table>
  <input type="submit" name="submit">
</form>

reddit-clone/app/views/subs/edit.html.erb
<h1>Edit <%= @sub.title %></h1>

<%= render 'shared/errors' %>
<%= render 'form', sub: @sub %>

reddit-clone/app/views/subs/index.html.erb
<h2>All Subs</h2>
<table>
  <tr>
    <th>
      Title
    </th>
    <th>
      Description
    </th>
    <th>
      Moderator
    </th>
  </tr>
  <% @subs.each do |sub| %>
  <tr>
    <td>
      <a href="<%= sub_url(sub) %>"><%= sub.title %></a>
    </td>
    <td>
      <%= sub.description %>
    </td>
    <td>
      <a href="<%= user_url(sub.moderator_id) %>"><%= sub.moderator.username %></a>
    </td>
  </tr>
  <% end %>
</table>

reddit-clone/app/views/subs/new.html.erb
<h1>Make a Sub!</h1>

<%= render 'shared/errors' %>
<%= render 'form', sub: @sub %>

reddit-clone/app/views/subs/show.html.erb
<%= render 'shared/errors' %>

<h1><%= @sub.title %></h1>
<p>
  Moderated by: <%= @sub.moderator.username %>
</p>
<h3>Description:</h3>
<p>
  <%= @sub.description %>
</p>
<% if @sub.moderator_id == current_user.id %>
  <a href="<%= edit_sub_url(@sub) %>">Edit this Sub</a>
<% end %>
<table>
  <tr>
    <th>
      Title
    </th>
    <th>
      Author
    </th>

  </tr>
  <% @posts.each do |post| %>
    <tr>
      <td>
        <% link_to_content = (post.url.nil? ? post_url(post) : post.url) %>
        <a href="<%= link_to_content %>"><%= post.title %></a>
      </td>
      <td>
        <a href="<%= user_url(post.author_id) %>"><%= post.author.username %></a>
      </td>
      <td>
        <% if post.author_id == current_user.id %>
          <a href=" <%= edit_post_url(post) %> ">Edit</a>
        <% end %>
      </td>
    </tr>
  <% end %>

</table>

<a href=" <%= new_sub_post_url(@sub) %> ">Add a Post to this Sub</a>